<%
  # See README for setup notes.
  # See https://github.com/NUBIC/bcdatabase for more info about bcdatabase.
  require 'bcdatabase'
  ENV['BCDATABASE_PATH'] ||= "#{ENV['HOME']}/.rails4_bcdatabase"
  bcdb = Bcdatabase.load
%>

<%= bcdb.development :local_mysql, :rails4_review %>
<%= bcdb.test :local_mysql, :rails4_review_test %>

<%= bcdb.production :production_mysql, :rails4_review_production %>